### ISSUE TITLE
Can't get bundles working

### ISSUE THREAD

**Issue by dodge107** [gizburdt/cuztom#378]
Any chance of a working example of bundles with some fields? 

Here is what I have tried, but all I get are blank bundles and the following vue error on the console.

```
[Vue warn]: Invalid expression. Generated function body:  (&&scope.list.length>=)||scope.loading
```

```
$fields = array(
				array(
					'id'	=> 'data_example',
					'label'	=> 'Example',
					'type'	=> 'text',

				),
				array(
					'id'	=> 'datadfd_example',
					'label'	=> 'Example',
					'type'	=> 'text',

				)
			);

$itineraries = register_cuztom_meta_box(
		'_itinerariesMeta',
		$cpt_name,
		array(
			'title' 	=> 	__('Data', 'cuztom'),  
			'fields' => array(
						array(
							'id'=> uniqid(),
							'type' => 'bundle',
							'fields' => $fields
					)
				)
		)	
);
```

**Comment by gizburdt** [comment]
You're code looks fine. This error is related to https://github.com/gizburdt/cuztom/issues/376. I'm working on a fix. Sorry for the inconvenience

**Comment by dodge107** [comment]
oh, no problem. :)

**Comment by gizburdt** [comment]
Hi, I think I fixed it. Can you test version 3.0.3?

More about bundles, and all other fields, you can find here https://cuztom.readme.io/docs/bundle

**Comment by dodge107** [comment]
Still the same issue my side after updating - confirmed the version is 3.0.3.

**Comment by gizburdt** [comment]
Forget to tell yesterday.. uniqid() is causing problems. Can you set an ID yourself? I changed the docs already.

**Comment by dodge107** [comment]
I saw that, I did set an id. It works if you only have one bundle on the page. I set unique ids for all of them and the sub-fields...

**Comment by gizburdt** [comment]
OK, I will have a look :)

**Comment by gizburdt** [comment]
Can you check version 3.0.4? Please let me know :)
